apps/login/urls.py
''' App URLS.py file. '''
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

apps/quotes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^newQuote$', views.newQuote, name="newQuote"),
    url(r'^addFavorite$', views.addFavorite, name="addFavorite"),
    url(r'^removeFavorite$', views.removeFavorite, name="removeFavorite"),
    url(r'^showUser/(?P<userid>\d+)$', views.showUser, name="showUser"),
]

quotablequotes/urls.py
"""quotablequotes URL Configuration
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^quotes/', include('apps.quotes.urls', namespace="quotes")),
    url(r'^', include('apps.login.urls', namespace="auth")),
]

apps/quotes/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import User

class QuoteManager(models.Manager):
    def insertnewquote(self, postData):
        """data validations on new quotes being added. """
        errors = []
        if len(postData['quoteby']) < 3:
            errors.append('Quote by needs to be more than 3 characters')
        if len(postData['quotemessage']) < 10:            
            errors.append('Quote Message must be at least 10 characters')               
        if 'createdBy' in postData:
            user = User.objects.get(id=postData['createdBy'])
            newquotecreate = Quote.objects.create(
                quoted_by=postData['quoteby'],
                message=postData['quotemessage'],
                created_by=user)
        return errors

    def insertfavorite(self, postData):
        """ moves a quote to the users favorites."""
        results = {'status': True, 'errors': []}
        user = User.objects.get(id=postData['createdBy'])
        quote = Quote.objects.get(id=postData['quoteid'])
        quote.favorite.add(user.id)
        return results

    def removefavorite(self, postData):
        """ moves a quote back to the main library """
        results = {'status': True, 'errors': []}
        user = User.objects.get(id=postData['createdBy'])
        quote = Quote.objects.get(id=postData['quoteid'])
        quote.favorite.remove(user.id)
        return results

class Quote(models.Model):
    quoted_by = models.CharField(max_length=150)
    message = models.CharField(max_length=500)
    created_by = models.ForeignKey(User, related_name="Quotes")
    favorite = models.ManyToManyField(User, related_name="Favorites")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = QuoteManager()

    def __str__(self):
        return str(self.id)
    

apps/quotes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import User
from models import Quote

def index(request):
    try:
        request.session['id']
    except KeyError:
        request.session.flush()
        messages.error(request, 'There is user session detected, please login.')
        return redirect('auth:index')
    loggedinuser = User.objects.get(id=request.session['id'])
    favoritequote = Quote.objects.filter(favorite = request.session['id'])
    quotablequotes = Quote.objects.all().exclude(favorite = request.session['id'])
    context = {
        'loggedinuser': loggedinuser,
        'quotablequotes': quotablequotes,
        'favoritequotes': favoritequote
    }
    return render(request, 'quotes/index.html', context)

def newQuote(request):
    insertnewquote = Quote.objects.insertnewquote(request.POST)
    if len(insertnewquote) > 0:
        for error in insertnewquote:
            messages.error(request, error)
            print error
    return redirect('/quotes')
        

    # return redirect('quotes:index')

def addFavorite(request):
    insertfavorite = Quote.objects.insertfavorite(request.POST)
    if not insertfavorite['status']:
        for error in insertfavorite['errors']:
            messages.error(request, error)
    return redirect('quotes:index')

def removeFavorite(request):
    removefavorite = Quote.objects.removefavorite(request.POST)
    if not removefavorite['status']:
        for error in removefavorite['errors']:
            messages.error(request, error)
    return redirect('quotes:index')

def showUser(request, userid):
    try:
        request.session['id']
    except KeyError:
        request.session.flush()
        messages.error(request, 'There is user session detected, please login.')
        return redirect('auth:index')
    user = User.objects.get(id=userid)
    quotes = Quote.objects.filter(created_by=userid)
    context = {
        'user': user,
        'quotes': quotes
    }
    return render(request, 'quotes/showUser.html', context)

apps/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Quotable Quotes</title>
        <meta description='Main Page for Quotable Quotes App'
        <meta charset='utf-8'/>
    </head>
    <body>
        <div id='wrapper'>
            <div id="header">
                <h1>Welcome, {{ loggedinuser.fname }}!</h1>
                <form action="{% url 'auth:logout' %}" id="logoutform" method="post">
                    {% csrf_token %}
                    <input type="submit" name="logoutbutton" value="Log Out">
                </form>        
            </div>
            <div>
                <h3>Your Favorites</h3>
                <hr>
                <table border>
                    <tr>
                        <th>Quote By:</th>
                        <th>Quote:</th>
                        <th>Submitted by:</th>
                        <th>Remove from Favorites</th>
                    </tr>
                {% for quote in favoritequotes %}
                    <tr>
                        <td>{{ quote.quoted_by }}</td>
                        <td>{{ quote.message }}</td>
                        <td><a href="{% url 'quotes:showUser' quote.created_by.id %}">{{ quote.created_by.alias }}</a></td>
                        <td>
                            <form action="{% url 'quotes:removeFavorite' %}" id="removeFavorite" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="createdBy" value="{{ loggedinuser.id }}">
                                <input type="hidden" name="quoteid" value="{{ quote.id }}">                 
                                <input type="submit" name="removeFavoriteButton" value="Remove Favorite">
                            </form>
                        </td>
                    </tr>
                {% endfor %}                    
                </table>
            </div>
            <div id="contributequote">
                <h3>Contribute a Quote:</h3>
                <hr>
                <form action="{% url 'quotes:newQuote' %}" id="newquoteform" method="post">
                    {% csrf_token %}
                    <label for="quoteby">Quote By:</label>
                    <input type="text" name="quoteby"><br><br>
                    <label for="quotemessage">Message:</label>
                    <textarea name="quotemessage" id="quotemessage" cols="50" rows="4"></textarea><br><br>
                    <input type="hidden" name="createdBy" value="{{ loggedinuser.id }} ">                    
                    <input type="submit" name="newQuoteButton" value="Submit">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </form>    
            </div id="quotablequotes">
            <div>
                <h3>Quotable Quotes</h3>
                <hr>
                <table border>
                    <tr>
                        <th>Quote By:</th>
                        <th>Quote:</th>
                        <th>Submitted by:</th>
                        <th>Add to Favorites</th>
                    </tr>
                {% for quote in quotablequotes %}
                    <tr>
                        <td>{{ quote.quoted_by }}</td>
                        <td>{{ quote.message }}</td>
                        <td><a href="{% url 'quotes:showUser' quote.created_by.id %}">{{ quote.created_by.alias }}</td>
                        <td>
                            <form action="{% url 'quotes:addFavorite' %}" id="addFavorite" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="createdBy" value="{{ loggedinuser.id }}">
                                <input type="hidden" name="quoteid" value="{{ quote.id }}">                 
                                <input type="submit" name="addFavoriteButton" value="Add to Favorites">
                            </form>
                        </td>
                    </tr>
                {% endfor %}                    
                </table>
            </div>
        </div>
    </body>
</html>

apps/quotes/templates/quotes/showUser.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>{{ user.alias }}'s Quotable Quotes</title>
        <meta description='Quotable Quotes App page for one user '>
        <meta charset='utf-8'/>
    </head>
    <body>
        <div id='wrapper'>
            <div id="header">
                <h1>Posts by {{ user.alias }}</h1>
                <h3>Count: {{ quotes.count }}</h3>
                <form action="{% url 'quotes:index' %}" id="dashboard" method="post">
                    {% csrf_token %}
                    <input type="submit" name="dashboardbutton" value="Dashboard">
                </form>        
                <form action="{% url 'auth:logout' %}" id="logoutform" method="post">
                    {% csrf_token %}
                    <input type="submit" name="logoutbutton" value="Log Out">
                </form>
                <hr>
                <table border>
                    <tr>
                        <th>Quotes Submitted</th>
                    </tr>
                {% for quote in quotes %}
                    <tr>
                        <td><strong>{{ quote.quoted_by }}:</strong> {{ quote.message }}</td>
                    </tr>
                {% endfor %}                    
                </table>      
            </div>
        </div>
    </body>
</html>