apps/login/urls.py
''' App URLS.py file. '''
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

quotablequotes/urls.py
"""quotablequotes URL Configuration
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^quotes/', include('apps.quotes.urls', namespace="quotes")),
    url(r'^', include('apps.login.urls', namespace="auth")),
]

apps/login/models.py
"""
This is the main processing model for the login/registration app. 
All user login and registration validations are done here. 
"""
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime
import re
from django.db import models
import bcrypt


# Create your models here.
class UserManager(models.Manager):
    def registervalidate(self, postData):
        """Main registration validations"""
        results = {'status': True, 'errors': [], 'user': None}
        if not postData['fname'] or len(postData['fname']) < 3:
            results['errors'].append("First Name must be at least 3 characters")
            results['status'] = False
        if not postData['lname'] or len(postData['lname']) < 3:
            results['errors'].append("Last Name must be at least 3 characters")
            results['status'] = False
        if not postData['alias'] or len(postData['alias']) < 3:
            results['errors'].append("Alias must be at least 3 characters")
            results['status'] = False
        if not postData['email'] or \
            not re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", postData['email']):
            results['errors'].append("Email Address is not valid")
            results['status'] = False
        if not postData['dob']:
            results['errors'].append("Birthday is required")
            results['status'] = False
        if not postData['userpassword'] or len(postData['userpassword']) < 8:
            results['errors'].append("Password must be at least 8 characters")
            results['status'] = False
        if postData['cpassword'] != postData['userpassword']:
            results['errors'].append("Passwords do not match")
            results['status'] = False
        user = User.objects.filter(email=postData['email'])
        if user:
            results['status'] = False
            results['errors'].append("Registration Failure, have you tried to login?")
        if results['status'] is False:
            return results
        if results['status']:
            userpassword = bcrypt.hashpw(postData['userpassword'].encode(), bcrypt.gensalt())
            user = User.objects.create(
                fname=postData['fname'],
                lname=postData['lname'],
                email=postData['email'],
                dob=postData['dob'],
                alias=postData['alias'],
                userpassword=userpassword)
            results['user'] = user
        return results

    def loginvalidate(self, postData):
        """login only validations"""
        results = {'status': True, 'errors': [], 'user': None}
        try:                # need this try loop if the db is empty.
            user = User.objects.filter(email=postData['email'])
            user[0] #This is an extra test to make sure the data is present
        except:
            results['status'] = False
            results['errors'].append("Account or password failure.")
            return results
        if user[0]:
            if user[0].userpassword != bcrypt.hashpw(postData['userpassword'].encode(),
                                                     user[0].userpassword.encode()):
                results['status'] = False
                results['errors'].append("Account or password failure.")
            else:
                results['user'] = user[0].id
        else:
            results['status'] = False
        return results


class User(models.Model):
    fname = models.CharField(max_length=100)
    lname = models.CharField(max_length=100)
    alias = models.CharField(max_length=255, unique=True)
    email = models.CharField(max_length=100, unique=True)
    userpassword = models.CharField(max_length=100)
    dob = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id)
    objects = UserManager()

apps/login/views.py
"""
The login app has 4 functions to assist the user, including
registering, and login. Registration validations are in the
model.py for the login app.
"""
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User

def index(request):
    """This is the main index page"""
    if request.session.get('id'):
        return redirect('quotes:index')
    return render(request, 'login/index.html')

def register(request):
    """When a user registers, send to model"""
    results = User.objects.registervalidate(request.POST)
    if not results['status']:
        for error in results['errors']:
            messages.error(request, error)
            return redirect('auth:index')
    request.session['id'] = results['user'].id
    return redirect('quotes:index')

def login(request):
    """When user logs in, send to model for validations"""
    results = User.objects.loginvalidate(request.POST)
    if results['status'] is False:
        for error in results['errors']:
            messages.error(request, error)
        return redirect('auth:index')
    else:
        user = User.objects.get(id=results['user'])
        request.session['id'] = user.id
    return redirect('quotes:index')

def logout(request):
    """Logout will flush session data!!!"""
    request.session.flush()
    messages.success(request, 'Logged Out')
    return redirect('auth:index')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>Quotes Application</title>
    </head>
    <body>
        <div id='wrapper'>
            <h1>Welcome to Quotes Application!</h1>
            <h2>Register</h2>
                <ul class="messages">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
            <form action="{% url 'auth:register' %}" id="registerform" method="post">
                {% csrf_token %}
                <label for="fname">First Name:</label>
                <input type="text" name="fname" autofocus><br><br>
                <label for="lname">Last Name:</label>
                <input type="text" name="lname"><br><br>
                <label for="alias">Alias:</label>
                <input type="text" name="alias"><br><br>
                <label for="email">Email:</label>
                <input type="text" name="email"><br><br>
                <label for="userpassword">Password:</label>
                <input type="password" name="userpassword"><br><br>
                <label for="cpassword">Confirm Password:</label>
                <input type="password" name="cpassword"><br>
                <p><font size='2'><i>*Password should be at least 8 characters</i></font></p> 
                <label for="dob">Date of Birth:</label>
                <input type="date" name="dob"><br><br>
                <input type="submit" name="registerbutton" value="Register">
            </form> 
            <h2>Login</h2>
            <form action="{% url 'auth:login' %}" id="loginform" method="post">
                {% csrf_token %}
                <label for="email">Email:</label>
                <input type="text" name="email"><br><br>
                <label for="userpassword">Password:</label>
                <input type="password" name="userpassword"><br><br>
                <input type="submit" name="registerbutton" value="Login">
            </form>        
        </div>
    </body>
</html>